### ISSUE TITLE
Documenting Backend Functions using Swagger

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#136]
As a backend team, we need to document API functions so that other team members can easily understand our API functions without digging into the code. 

[Swagger](https://swagger.io/) is very good and popular tool for this.

[This article](https://django-rest-swagger.readthedocs.io/en/latest/) shows how to add this tool to the Django framework.

**Comment by MrLebowski42** [comment]
Unexpectedly, most of the auto documentation tools require Django Rest Framework utilization. This tool provides many functionalities that would be very beneficial for our development. Since this milestone will be a base for our project, we should build our Backend with respect to this framework early on. I created an additional issue for this task #141

**Comment by emrahdgn** [comment]
We had a meeting with Berke last night and we tried to implement the swagger integration in [this](https://www.section.io/engineering-education/django-api-documentation/) way, there was no parameter section and all functions are failing in an interesting way. 

In [this video links](https://www.youtube.com/channel/UCTUNjMU2tqoe3CWz1t9GuRQ/videos), author implemented code in a different manner. It may also help.

But implementing the backend with Django Rest Framework is also a good idea at the beginning of the project.

**Comment by emrahdgn** [comment]
We implemented backend with Django Rest Framework and solved Swagger documentations problems with Berke.
Swagger documentation is also available. There is nothing left to be done about it. Therefore i am closing this issue.
