### ISSUE TITLE
Research on map & geocoding APIs

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#186]
As we are planning to add location data field support, we need to use an third-party API like Google Maps, Bing Maps. Since this task is concerning all of the sub teams, I'm assigning it to the whole team. [Here ](https://github.com/public-apis/public-apis#geocoding)is  list with links and descriptions for some public geocoding APIs.

My personal suggestion is using [Google Maps Platform](https://developers.google.com/maps/gmp-get-started) as it includes many APIs like:

- [Geocoding API](https://developers.google.com/maps/documentation/geocoding/overview) for translating coordinates to human-readable adresses or vice versa.
- [Maps Javascript API](https://developers.google.com/maps/documentation/javascript/overview) for generating interactible maps in application.

Please comment your API suggestions with some explanation and links to its documentation.

**Comment by yunus-topal** [comment]
if we just need coordinates, there is openweather.org which show weather conditions for some places but also returns coordinates for that place. It works with both city names and country names.

**Comment by emrahdgn** [comment]
The location information openweather.org provides is probably not detailed enough. For map services, I think we should focus on services such as Google Maps or Yandex Maps, which are good in this field.

I am in favor of choosing the Google Maps option as it is widely used by many people. There are many tutorials that will definitely help us with this.

**Comment by gktpmuhammed** [comment]
Implementation of the location feature is completed now. We are using [Google Maps Javascript API](https://developers.google.com/maps/documentation/javascript/overview) as an interactive map. We are using several functionalities from API. We have implemented [use-places-autocomplete API](https://developers.google.com/maps/documentation/javascript/places-autocomplete) for searching and retrieving addresses. We used Marker for displaying the selected location. We also used [Reverse Geocoding API](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse) for displaying human-readable addresses of locations. 
Since the implementation is finished I am closing this issue.
