### ISSUE TITLE
Location should be implemented

### ISSUE THREAD

**Issue by 4teko7** [bounswe/2021SpringGroup1#239]
Users should share their location. We should see the location of the users who share posts in the communities.
Longitude and Latitude are very important parts for location. We will use these two fields to find the location of the users.

We should get the physical address of the users only once because for all request to Google Maps, we will be charged. Therefore, we will save the Longitude and Latitude as well as the physical address and we will show the physical address in the screens. We will save Longitude and Latitude in case of any issue, we can use these.

**Comment by gktpmuhammed** [comment]
Implementation of the location feature is completed now. We are using [Google Maps Javascript API](https://developers.google.com/maps/documentation/javascript/overview) as an interactive map. We are using several functionalities from API. We have implemented [use-places-autocomplete API](https://developers.google.com/maps/documentation/javascript/places-autocomplete) for searching and retrieving addresses. We used Marker for displaying the selected location. We also used [Reverse Geocoding API](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse) for displaying human-readable addresses of locations. 
Since the implementation is finished I am closing this issue.
